[project]
name = "transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "flask",
    "openai==1.81.0",
    "python-dotenv",
    "streamlit>=1.45.1",
    "dotenv>=0.9.9",
]

